-- ============================================================
-- pathFollower.lua
-- Target-following execution and trajectory metrics for CoppeliaSim
-- ------------------------------------------------------------
-- This script waits for a new path generated by the OMPL planner,
-- reads the packed XYZ path stored in the /Path custom data blocks,
-- moves the quadrotor target along the planned trajectory, and reports
-- execution metrics for experimental benchmarking.
--
-- Main outputs:
--   t_target_s    : simulated time required by the target to traverse the path.
--   t_drone_s     : simulated time required by the drone body to reach the goal.
--   wall_exec_s   : real wall-clock execution time of this script.
--   arrival_err_m : final Euclidean distance between the drone body and the goal.
--   reached       : true if the drone body reaches the final waypoint tolerance.
--
-- Expected data blocks written by Path_Planner.lua:
--   OMPL_READY
--   OMPL_XYZ_PATH
--   OMPL_PATH_ID
--   OMPL_ITER_SOLVED
--   OMPL_PLAN_TIME
--   OMPL_PATH_LENGTH
--   OMPL_WAYPOINTS
-- ============================================================

sim = require 'sim'

-- ============================================================
-- Execution configuration
-- ------------------------------------------------------------
-- These parameters define the target-following behavior and the
-- acceptance criterion used to report whether the drone reached the
-- final waypoint. They can be modified to reproduce different
-- experimental conditions.
-- ============================================================

-- Desired target speed in meters per second.
-- This value must match the speed reported in the paper and CSV logs.
local SPEED_MPS = 0.30

-- Euclidean tolerance used to decide whether the drone body reached
-- the final waypoint. A smaller value is stricter but may increase
-- failed executions if the simulated drone oscillates near the goal.
local ARRIVAL_TOL_M = 0.10

-- Additional waiting time after the target reaches the last waypoint.
-- This allows the physical/simulated drone body to converge to the goal.
local ARRIVAL_TIMEOUT_S = 10.0

-- If true, the script attempts to measure the arrival time of the drone
-- body. If false, only the target traversal time is reported.
local CHECK_REAL_DRONE_ARRIVAL = true


-- ============================================================
-- Geometry utilities
-- ============================================================

-- Computes the Euclidean distance between two 3D points.
-- Points are represented as Lua tables: {x, y, z}.
local function dist(a, b)
    local dx = a[1] - b[1]
    local dy = a[2] - b[2]
    local dz = a[3] - b[3]
    return math.sqrt(dx * dx + dy * dy + dz * dz)
end

-- Computes the total path length from a waypoint list.
-- Each waypoint is represented as {x, y, z}.
local function pathLengthWP(wp)
    local L = 0
    for k = 1, #wp - 1 do
        L = L + dist(wp[k], wp[k + 1])
    end
    return L
end


-- ============================================================
-- Scene object lookup
-- ============================================================

-- Locates the quadrotor target object.
-- Update this list if the CoppeliaSim drone model uses a different
-- target object name.
local function getTarget()
    local h = sim.getObject('/target', {noError = true})
    if h ~= -1 then return h end

    h = sim.getObject('/Quadcopter_target', {noError = true})
    if h ~= -1 then return h end

    h = sim.getObject('/Quadcopter/target', {noError = true})
    return h
end

-- Locates the drone body or base object used to measure real arrival.
-- The target may reach the final waypoint before the drone body does.
-- Therefore, this handle is used to distinguish target traversal time
-- from drone arrival time.
--
-- Add or modify object paths in the candidate list if a different
-- quadrotor model is used.
local function getDroneBody()
    local candidates = {
        '/Quadcopter',
        '/Quadcopter/body',
        '/Quadcopter/base',
        '/Quadcopter/respondable',
        '/drone',
        '/Drone'
    }

    for i = 1, #candidates do
        local h = sim.getObject(candidates[i], {noError = true})
        if h ~= -1 then return h end
    end

    return -1
end


-- ============================================================
-- Custom-data block readers
-- ------------------------------------------------------------
-- The planner communicates with this follower by writing custom data
-- blocks to the /Path object. These helper functions provide robust
-- access to integer and floating-point blocks.
-- ============================================================

-- Reads the OMPL_READY flag.
--   0: no new path is available.
--   1: a new path has been generated and can be executed.
local function readReady(pathHandle)
    local r = sim.readCustomDataBlock(pathHandle, 'OMPL_READY')
    if not r then return nil end
    return sim.unpackInt32Table(r)[1]
end

-- Reads an integer custom-data block. If the block does not exist,
-- defaultValue is returned.
local function readIntBlock(pathHandle, tag, defaultValue)
    local p = sim.readCustomDataBlock(pathHandle, tag)
    if not p then return defaultValue end
    return sim.unpackInt32Table(p)[1]
end

-- Reads a floating-point custom-data block. If the block does not exist,
-- defaultValue is returned.
local function readFloatBlock(pathHandle, tag, defaultValue)
    local p = sim.readCustomDataBlock(pathHandle, tag)
    if not p then return defaultValue end
    return sim.unpackFloatTable(p)[1]
end


-- ============================================================
-- Main threaded callback
-- ============================================================

function sysCall_thread()
    local target = getTarget()
    if target == -1 then
        error('Drone target was not found. Update getTarget() with the correct CoppeliaSim object path.')
    end

    local droneBody = getDroneBody()
    local pathHandle = sim.getObject('/Path')

    -- --------------------------------------------------------
    -- 1) Wait for the planner to invalidate the previous path.
    -- --------------------------------------------------------
    -- Path_Planner.lua sets OMPL_READY = 0 at the beginning of each
    -- planning run. This avoids executing a stale trajectory from a
    -- previous experiment.
    while true do
        local ready = readReady(pathHandle)
        if ready == 0 then break end
        sim.step()
    end

    -- --------------------------------------------------------
    -- 2) Wait for a new path generated by OMPL.
    -- --------------------------------------------------------
    -- A valid path is available only when OMPL_READY = 1 and the
    -- OMPL_XYZ_PATH custom-data block exists.
    local xyz = nil
    while true do
        local ready = readReady(pathHandle)
        local p = sim.readCustomDataBlock(pathHandle, 'OMPL_XYZ_PATH')
        if ready == 1 and p then
            xyz = sim.unpackFloatTable(p)
            break
        end
        sim.step()
    end

    -- --------------------------------------------------------
    -- 3) Convert the packed XYZ vector into a waypoint list.
    -- --------------------------------------------------------
    -- The planner stores the path as a flat sequence:
    --   {x1, y1, z1, x2, y2, z2, ...}
    -- This section converts it into:
    --   {{x1, y1, z1}, {x2, y2, z2}, ...}
    local wp = {}
    for i = 1, #xyz, 3 do
        wp[#wp + 1] = {xyz[i], xyz[i + 1], xyz[i + 2]}
    end

    if #wp < 2 then
        sim.addLog(sim.verbosity_errors, 'pathFollower: invalid path. At least two waypoints are required.')
        return
    end

    -- --------------------------------------------------------
    -- Retrieve planning metrics written by Path_Planner.lua.
    -- --------------------------------------------------------
    -- If a metric is not available, a fallback value is computed or
    -- assigned locally. This makes the script robust to partial logs.
    local pathId = readIntBlock(pathHandle, 'OMPL_PATH_ID', -1)
    local iterPlan = readIntBlock(pathHandle, 'OMPL_ITER_SOLVED', -1)
    local tPlan = readFloatBlock(pathHandle, 'OMPL_PLAN_TIME', -1.0)
    local pathLen = readFloatBlock(pathHandle, 'OMPL_PATH_LENGTH', pathLengthWP(wp))
    local nWp = readIntBlock(pathHandle, 'OMPL_WAYPOINTS', #wp)

    local dt = sim.getSimulationTimeStep()
    local tExec0 = sim.getSimulationTime()
    local wallExec0 = sim.getSystemTimeInMs(-1)

    -- --------------------------------------------------------
    -- 4) Execute the path by moving the quadrotor target.
    -- --------------------------------------------------------
    -- For each segment, the target is linearly interpolated between
    -- consecutive waypoints. The number of interpolation steps is
    -- derived from the desired speed and the simulation time step.
    --
    -- Variant parameter:
    --   SPEED_MPS controls how fast the target moves along the path.
    --   Increasing it reduces t_target_s but may make the drone body
    --   lag behind the target.
    for k = 1, #wp - 1 do
        local p1 = wp[k]
        local p2 = wp[k + 1]
        local d = dist(p1, p2)
        local T = d / SPEED_MPS

        -- math.ceil prevents the target from moving faster than
        -- SPEED_MPS due to time-step rounding.
        local steps = math.max(1, math.ceil(T / dt))

        for i = 1, steps do
            local s = i / steps

            -- Linear interpolation between p1 and p2.
            -- This defines a piecewise-linear trajectory following the
            -- OMPL path. Replace this block if a different trajectory
            -- type is required, such as spline smoothing or minimum-jerk
            -- interpolation.
            local p = {
                p1[1] * (1 - s) + p2[1] * s,
                p1[2] * (1 - s) + p2[2] * s,
                p1[3] * (1 - s) + p2[3] * s
            }

            sim.setObjectPosition(target, p)
            sim.step()
        end
    end

    -- Target traversal time measured in simulated seconds.
    local tTargetS = sim.getSimulationTime() - tExec0

    -- --------------------------------------------------------
    -- 5) Measure the real drone-body arrival to the final waypoint.
    -- --------------------------------------------------------
    -- The target and the drone body are not necessarily colocated.
    -- This block waits until the drone body reaches the final waypoint
    -- or until the additional timeout is exceeded.
    --
    -- Variant parameters:
    --   CHECK_REAL_DRONE_ARRIVAL enables or disables this measurement.
    --   ARRIVAL_TOL_M defines the spatial tolerance around the final goal.
    --   ARRIVAL_TIMEOUT_S defines the maximum additional waiting time.
    local finalGoal = wp[#wp]
    local reached = false
    local arrivalErr = -1.0
    local tDroneS = tTargetS

    if CHECK_REAL_DRONE_ARRIVAL and droneBody ~= -1 then
        local waitStart = sim.getSimulationTime()

        while true do
            local dronePos = sim.getObjectPosition(droneBody)
            arrivalErr = dist(dronePos, finalGoal)

            if arrivalErr <= ARRIVAL_TOL_M then
                reached = true
                tDroneS = sim.getSimulationTime() - tExec0
                break
            end

            if (sim.getSimulationTime() - waitStart) >= ARRIVAL_TIMEOUT_S then
                tDroneS = sim.getSimulationTime() - tExec0
                break
            end

            sim.step()
        end
    else
        -- If the drone body cannot be located, only the target traversal
        -- time is reported. In this case, reached remains false because
        -- body-level arrival cannot be verified.
        reached = false
        arrivalErr = -1.0
        tDroneS = tTargetS
    end

    local wallExecS = sim.getSystemTimeInMs(wallExec0) / 1000.0

    -- --------------------------------------------------------
    -- 6) Print the final execution report.
    -- --------------------------------------------------------
    -- This log line is intentionally formatted as a compact record so it
    -- can be copied to a CSV file or parsed during batch experiments.
    sim.addLog(sim.verbosity_scriptinfos,
        string.format(
            'DRONE EXEC OK: PATH_ID=%d | iter_plan=%d | t_plan_s=%.3f | pathLen_m=%.3f | waypoints=%d | speed_mps=%.3f | t_target_s=%.3f | t_drone_s=%.3f | wall_exec_s=%.3f | arrival_err_m=%.3f | reached=%s',
            pathId,
            iterPlan,
            tPlan,
            pathLen,
            nWp,
            SPEED_MPS,
            tTargetS,
            tDroneS,
            wallExecS,
            arrivalErr,
            tostring(reached)
        )
    )
end
